package raf.dsw.gerumap.app.mapRepository.composite;

public enum MapNodeNotificationType {
    PROJECT_ADDED, PROJECT_RENAMED, PROJECT_AUTHOR_CHANGE, PROJECT_REMOVED, MIND_MAP_ADDED, MIND_MAP_REMOVED, MIND_MAP_RENAMED, ELEMENT_ADDED, ELEMENT_REMOVED, LINK_FROM_CHANGED, LINK_TO_CHANGED, ELEMENT_STYLE_CHANGED, TERM_MOVED, MIND_MAP_TEMPLATE_STATUS_CHANGED, TERM_CENTRAL_CHANGED, ELEMENT_RENAMED
}
