package raf.dsw.gerumap.app.messageGenerator;

public enum MessageType {
    NODE_CANNOT_BE_DELETED, NAME_CANNOT_BE_EMPTY, A_PROJECT_MUST_BE_SELECTED, NAME_ALREADY_USED, NOTHING_SELECTED, FILE_NOT_FOUND, FAILED_TO_WRITE_FILE, FAILED_TO_READ_FILE, MULTIPLE_SELECTED, NO_TERMS_SELECTED, NO_VALID_NODE
}
